name: terraform
on:
  push:
    branches:
    - main
  pull_request:
    branches: 
    - main
jobs:
  fmt_validate_terraform:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.5.5
    steps:
    - uses: actions/checkout@v4.1.0
    - name: terraform init
      run: for d in */ ; do (cd "$d" && terraform init -input=false -no-color -backend=false); done
    - name: terraform fmt
      run: for d in */ ; do (cd "$d" && terraform fmt -no-color -check -diff -recursive=true); done
    - name: terraform validate
      run: for d in */ ; do (cd "$d" && terraform validate -no-color); done
